<footer
  class="flex flex-col-reverse md:flex-row justify-center gap-y-6 md:justify-evenly items-center md:items-start py-12 md:p-28 bg-blue-600"
>
  <div
    class="w-[70vw] text-white text-sm md:text-left flex flex-col items-center md:items-start"
  >
    <h1
      class="md:text-3xl font-bold text-xl mb-6 text-center md:text-left md:mb-14"
    >
      Hubungi kami
    </h1>
    <div class="flex flex-col gap-7 items-center md:items-start max-w-md">
      <a href="https://maps.app.goo.gl/ovsE9waxg5EroJpW9">
        <div class="flex gap-3 items-center">
          <img src="<?=BASEURL?>/assets/img/location.webp" alt="" />
          <h3>
            Dsn. Kejambon Ds. Gondang Kec. Gondang Kab. Mojokerto, Jawa Timur
          </h3>
        </div>
      </a>
      <a href="https://www.instagram.com/pt.hilaltrans">
        <div class="flex gap-2 items-center">
          <img
            src="<?=BASEURL?>/assets/img/teenyicons_instagram-solid.webp"
            alt=""
          />
          <h3>pt.hilaltrans</h3>
        </div>
      </a>
      <a href="https://www.youtube.com/channel/UCBzceAFPTSryLec-6jKYZhw">
        <div class="flex gap-2 items-center">
          <img src="<?=BASEURL?>/assets/img/simple-icons_youtube.webp" alt="" />
          <h3>Puma. Tour</h3>
        </div>
      </a>
      <a href="https://wa.me/6288803528451">
        <div class="flex gap-2 items-center">
          <img src="<?=BASEURL?>/assets/img/formkit_whatsapp.webp" alt="" />
          <h3>088803528451</h3>
        </div>
      </a>
    </div>
  </div>
  <iframe
    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4323.908650200603!2d112.49006259076637!3d-7.614320684708444!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e7873cf733e4c99%3A0xefeba1a30ca5c076!2sSMAS%20ISLAM%20DIPONEGORO%20GONDANG%20MOJOKERTO!5e0!3m2!1sid!2sid!4v1715310800182!5m2!1sid!2sid"
    class="w-3/4 sm:w-1/2 lg:w-[45%] aspect-square"
    style="border: 0"
    allowfullscreen=""
    loading="lazy"
    referrerpolicy="no-referrer-when-downgrade"
  ></iframe>
</footer>
<div class="w-full text-sm bg-black text-center p-3 text-white">
  Copyright 2024 | PT. Hilal Paripurna Purnama
</div>
<!-- =============================================== END FOOTER ================================================ -->

<script src="<?= BASEURL ?>/node_modules/flowbite/dist/flowbite.min.js"></script>
