<div class=""> 
    <div class="navbar">
        <div class="leftnavbar">
            <a href="<?php echo BASEURL; ?>/app/admin/index.php" class="logo"><img class="img-logo" src="<?php echo BASEURL; ?> /assets/img/logo.jpg" alt="logo"></a>
        </div>
        <nav class="rightnavbar">
            <ul>
                <li><a href="<?php echo BASEURL; ?>/app/admin/index.php">Dashboard</a></li>
                <li><a href="<?php echo BASEURL; ?>/app/admin/transaksi/index.php">Pemesanan</a></li>
                <li><a href="<?php echo BASEURL; ?>/app/armada/paket/index.php">Armada</a></li>
                <li><a href="<?php echo BASEURL; ?>/app/admin/paket/index.php">Paket Wisata</a></li>
                <li><a href="<?php echo BASEURL; ?>/app/admin/profile.php">Akun</a></li>
            </ul>
        </nav>
    </div>
</div>